language: cpp
compiler:
  - gcc
env:
  global:
    - GAPDOC=GAPDoc-1.5.1
    - GRAPE=grape4r7
    - DIGRAPHS_LIB=digraphs-lib-0.5
  matrix:
    # Run only `make lint'
    - LINT=1

    # Run Digraphs tests and manual examples
    # 64-bit, master (and the newest package versions, where possible)
    - GAP_BRANCH=master NEWEST=1
    # 32-bit, master (and the required package versions, where possible)
    - GAP_BRANCH=master GAP_FLAGS="ABI=32 --host=i686-linux-gnumake" PKG_FLAGS="CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 --host=i686-linux-gnu"
    # 64-bit, stable-4.8 (and the required package versions, where possible)
    - GAP_BRANCH=stable-4.8
    # 32-bit, stable-4.8 (and the required package versions, where possible)
    - GAP_BRANCH=stable-4.8 GAP_FLAGS="ABI=32 --host=i686-linux-gnumake" PKG_FLAGS="CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 --host=i686-linux-gnu"

    # Run with the required version of GAP and packages, where possible
    - GAP_BRANCH=required

    # Run code coverage
    - COVERAGE=1 THRESHOLD=98 GAP_BRANCH=master

    # TODO: Run Valgrind
    #- VALGRIND=1 GAP_BRANCH=master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5-multilib
before_script:
  - echo "deb http://us.archive.ubuntu.com/ubuntu/ vivid main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install libgmp-dev
  - sudo apt-get install libgmp-dev:i386
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
script:
  - scripts/travis-build.sh
  - scripts/travis-test.sh
